<?php

namespace Database\Seeders;
  
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
  
class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    // public function run()
    // {
    //     $permissions = [
    //        'role-list',
    //        'role-create',
    //        'role-edit',
    //        'role-delete',
    //        'posts-list',
    //        'posts-create',
    //        'posts-edit',
    //        'posts-delete'
    //     ];
      
    //     foreach ($permissions as $permission) {
    //          Permission::create(['name' => $permission]);
    //     }
    // }
     public function run()
    {
        $permissions = [
            'site-login',
            'context-dashboard',
            'context-developer',
            'context-settings',
            'mod-contexts-index',
            'mod-contexts-create',
            'mod-contexts-edit',
            'mod-contexts-delete',
            'mod-modules-index',
            'mod-modules-create',
            'mod-modules-edit',
            'mod-modules-delete',
            'mod-permissions-index',
            'mod-permissions-create',
            'mod-permissions-edit',
            'mod-permissions-delete',
            'mod-roles-index',
            'mod-roles-create',
            'mod-roles-edit',
            'mod-roles-delete',
            'mod-permissionsmatrix-index',
            'mod-permissionsmatrix-create',
            'mod-permissionsmatrix-edit',
            'mod-permissionsmatrix-delete',
            'mod-users-index',
            'mod-users-create',
            'mod-users-edit',
            'mod-users-delete',
            'mod-configurations-index',
            'mod-configurations-create',
            'mod-configurations-edit',
            'mod-configurations-delete',
            'context-maincontent',
            'mod-category-index',
            'mod-category-listall',
            'mod-category-create',
            'mod-category-edit',
            'mod-category-delete',
            'mod-mainmenu-index',
            'mod-mainmenu-listall',
            'mod-mainmenu-create',
            'mod-mainmenu-edit',
            'mod-mainmenu-delete',
            'mod-pages-index',
            'mod-pages-listall',
            'mod-pages-create',
            'mod-pages-edit',
            'mod-pages-delete',
            'mod-posts-index',
            'mod-posts-listall',
            'mod-posts-create',
            'mod-posts-edit',
            'mod-posts-delete',
            'mod-imageslider-index',
            'mod-imageslider-listall',
            'mod-imageslider-create',
            'mod-imageslider-edit',
            'mod-imageslider-delete',
            'mod-galeri-index',
            'mod-galeri-listall',
            'mod-galeri-create',
            'mod-galeri-edit',
            'mod-galeri-delete',
            'mod-album-index',
            'mod-album-listall',
            'mod-album-create',
            'mod-album-edit',
            'mod-album-delete',
            'mod-event-index',
            'mod-event-listall',
            'mod-event-create',
            'mod-event-edit',
            'mod-event-delete',
            'mod-video-index',
            'mod-video-listall',
            'mod-video-create',
            'mod-video-edit',
            'mod-video-delete',
            'mod-tautan-index',
            'mod-tautan-listall',
            'mod-tautan-create',
            'mod-tautan-edit',
            'mod-tautan-delete',
            'mod-majalah-index',
            'mod-majalah-listall',
            'mod-majalah-create',
            'mod-majalah-edit',
            'mod-majalah-delete',
            'context-masterdata',
            'mod-masteruser-index',
            'mod-masteruser-listall',
            'mod-masteruser-create',
            'mod-masteruser-edit',
            'mod-masteruser-delete',
            'mod-bukutamu-index',
            'mod-bukutamu-listall',
            'mod-bukutamu-create',
            'mod-bukutamu-edit',
            'mod-bukutamu-delete',
            'mod-tanggapan-index',
            'mod-tanggapan-listall',
            'mod-tanggapan-create',
            'mod-tanggapan-edit',
            'mod-tanggapan-delete',
            'mod-produkhukum-index',
            'mod-produkhukum-listall',
            'mod-produkhukum-create',
            'mod-produkhukum-edit',
            'mod-produkhukum-delete',
            'mod-runningtext-index',
            'mod-runningtext-listall',
            'mod-runningtext-create',
            'mod-runningtext-edit',
            'mod-runningtext-delete',
            'mod-utility-index',
            'mod-utility-listall',
            'mod-utility-create',
            'mod-utility-edit',
            'mod-utility-delete',
            'context-konsultasi',
            'mod-jeniskonsultasi-index',
            'mod-jeniskonsultasi-listall',
            'mod-jeniskonsultasi-create',
            'mod-jeniskonsultasi-edit',
            'mod-jeniskonsultasi-delete',
            'mod-kepegawaian-index',
            'mod-kepegawaian-listall',
            'mod-kepegawaian-create',
            'mod-kepegawaian-edit',
            'mod-kepegawaian-delete',
            'mod-response-index',
            'mod-response-listall',
            'mod-response-create',
            'mod-response-edit',
            'mod-response-delete',
            'mod-produkbkd-index',
            'mod-produkbkd-listall',
            'mod-produkbkd-create',
            'mod-produkbkd-edit',
            'mod-produkbkd-delete',
            'context-perizinan',
            'mod-masterizin-index',
            'mod-masterizin-listall',
            'mod-masterizin-create',
            'mod-masterizin-edit',
            'mod-masterizin-delete',
            'mod-detailizin-index',
            'mod-detailizin-listall',
            'mod-detailizin-create',
            'mod-detailizin-edit',
            'mod-detailizin-delete',
            'context-profilinstansi',
            'mod-sotk-index',
            'mod-sotk-listall',
            'mod-sotk-create',
            'mod-sotk-edit',
            'mod-sotk-delete',
            'mod-pejabat-index',
            'mod-pejabat-listall',
            'mod-pejabat-create',
            'mod-pejabat-edit',
            'mod-pejabat-delete',
            'mod-sejarah-index',
            'mod-sejarah-listall',
            'mod-sejarah-create',
            'mod-sejarah-edit',
            'mod-sejarah-delete',
            'context-investasi',
            'mod-masterinvestasi-index',
            'mod-masterinvestasi-listall',
            'mod-masterinvestasi-create',
            'mod-masterinvestasi-edit',
            'mod-masterinvestasi-delete',
            'mod-kategoriinvestasi-index',
            'mod-kategoriinvestasi-listall',
            'mod-kategoriinvestasi-create',
            'mod-kategoriinvestasi-edit',
            'mod-kategoriinvestasi-delete',
            'mod-konteninvestasi-index',
            'mod-konteninvestasi-listall',
            'mod-konteninvestasi-create',
            'mod-konteninvestasi-edit',
            'mod-konteninvestasi-delete',
            'context-ppid',
            'mod-menuutama-index',
            'mod-menuutama-listall',
            'mod-menuutama-create',
            'mod-menuutama-edit',
            'mod-menuutama-delete',
            'mod-sliderimage-index',
            'mod-sliderimage-listall',
            'mod-sliderimage-create',
            'mod-sliderimage-edit',
            'mod-sliderimage-delete',
            'mod-statistikperizinan-index',
            'mod-statistikperizinan-listall',
            'mod-statistikperizinan-create',
            'mod-statistikperizinan-edit',
            'mod-statistikperizinan-delete',
            'context-saranaprasarana',
            'mod-mastersarpras-index',
            'mod-mastersarpras-listall',
            'mod-mastersarpras-create',
            'mod-mastersarpras-edit',
            'mod-mastersarpras-delete',
            'mod-pengumuman-index',
            'mod-pengumuman-listall',
            'mod-pengumuman-create',
            'mod-pengumuman-edit',
            'mod-pengumuman-delete',
            'mod-testimonial-index',
            'mod-testimonial-listall',
            'mod-testimonial-create',
            'mod-testimonial-edit',
            'mod-testimonial-delete',
            'context-statistik',
            'mod-lpk-index',
            'mod-lpk-listall',
            'mod-lpk-create',
            'mod-lpk-edit',
            'mod-lpk-delete',
            'mod-potensitenagakerja-index',
            'mod-potensitenagakerja-listall',
            'mod-potensitenagakerja-create',
            'mod-potensitenagakerja-edit',
            'mod-potensitenagakerja-delete',
            'mod-potensitenagakerjasmk-index',
            'mod-potensitenagakerjasmk-listall',
            'mod-potensitenagakerjasmk-create',
            'mod-potensitenagakerjasmk-edit',
            'mod-potensitenagakerjasmk-delete',
            'mod-potensilpk-index',
            'mod-potensilpk-listall',
            'mod-potensilpk-create',
            'mod-potensilpk-edit',
            'mod-potensilpk-delete',
            'mod-realisasiperizinan-index',
            'mod-realisasiperizinan-listall',
            'mod-realisasiperizinan-create',
            'mod-realisasiperizinan-edit',
            'mod-realisasiperizinan-delete',
            'mod-sotkppid-index',
            'mod-sotkppid-listall',
            'mod-sotkppid-create',
            'mod-sotkppid-edit',
            'mod-sotkppid-delete',
            'mod-pejabatppid-index',
            'mod-pejabatppid-listall',
            'mod-pejabatppid-create',
            'mod-pejabatppid-edit',
            'mod-pejabatppid-delete',
            'mod-pengajuaninformasi-index',
            'mod-pengajuaninformasi-listall',
            'mod-pengajuaninformasi-create',
            'mod-pengajuaninformasi-edit',
            'mod-pengajuaninformasi-delete',
            'mod-pengajuankeberatan-index',
            'mod-pengajuankeberatan-listall',
            'mod-pengajuankeberatan-create',
            'mod-pengajuankeberatan-edit',
            'mod-pengajuankeberatan-delete',
            'context-uppd',
            'mod-menuutamauppd-index',
            'mod-menuutamauppd-listall',
            'mod-menuutamauppd-create',
            'mod-menuutamauppd-edit',
            'mod-menuutamauppd-delete',
           

        ];
      
        foreach ($permissions as $permission) {
             Permission::create(['name' => $permission]);
        }
    }

    
}
